[package]
name = "my_app"
version = "1.0.0"
edition.workspace = true

[[bin]]
name = "my_app"
path = "src/main.rs"

[lib]
name = "my_app"
path = "src/lib.rs"

[dependencies]
domain = { path = "../../lib/domain" }
infra = { path = "../../lib/infra" }
actix-web = { workspace = true, features = ["rustls"] }
actix-rt.workspace = true
actix-http.workspace = true
log.workspace = true
env_logger.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
async-trait.workspace = true
diesel = { workspace = true, features = ["postgres", "r2d2"] }
diesel_migrations.workspace = true
dotenv.workspace = true
r2d2.workspace = true
tokio = { workspace = true, features = ["full"] }
thiserror.workspace = true
derive_more.workspace = true
reqwest={ workspace = true, features = ["json"] }
mockall.workspace = true
uuid = { workspace = true, features = ["serde", "v4"] }
